parameters:
  tracker.enabled: '%env(bool:TRACKING_ENABLED)%'
  env(TRACKING_ENABLED): 'false'
  tracker.instrumentation_key: '%env(MICROSOFT_APP_INSIGHTS_INTRUMENTATION_KEY)%'
  env(MICROSOFT_APP_INSIGHTS_INTRUMENTATION_KEY): ''
  exceptions.tracking_enabled: '%env(bool:EXCEPTION_TRACKING_ENABLED)%'
  env(EXCEPTION_TRACKING_ENABLED): 'false'
  exceptions.tracking_ignore: '%env(json:EXCEPTION_TRACKING_IGNORE)%'
  env(EXCEPTION_TRACKING_IGNORE): '[]'

services:
  'tracker.exception_config':
     class: HalloVerden\ApplicationInsightsBundle\Tracker\Configuration\ExceptionConfiguration
     arguments:
       $enabled:           '%exceptions.tracking_enabled%'
       $ignoredExceptions: '%exceptions.tracking_ignore%'

  'tracker_config':
    class: HalloVerden\ApplicationInsightsBundle\Tracker\Configuration
    arguments:
      $enabled: '%tracker.enabled%'
      $key: '%tracker.instrumentation_key%'
      $exceptionConfiguration: '@tracker.exception_config'

  HalloVerden\ApplicationInsightsBundle\EventSubscriber\ExceptionSubscriber:
    tags: [ { name: kernel.event_subscriber } ]
    arguments:
      $tracker: '@HalloVerden\ApplicationInsightsBundle\Interfaces\TelemetryTrackerInterface'

  HalloVerden\ApplicationInsightsBundle\EventSubscriber\KernelTerminateSubscriber:
    tags: [ { name: kernel.event_subscriber } ]
    arguments:
      $tracker: '@HalloVerden\ApplicationInsightsBundle\Interfaces\TelemetryTrackerInterface'

  HalloVerden\ApplicationInsights\TelemetryClient:
    class: HalloVerden\ApplicationInsights\TelemetryClient

  HalloVerden\ApplicationInsightsBundle\Interfaces\TelemetryTrackerInterface:
    class: HalloVerden\ApplicationInsightsBundle\Tracker\TelemetryTracker
    arguments:
      $client:        '@HalloVerden\ApplicationInsights\TelemetryClient'
      $logger:        '@Psr\Log\LoggerInterface'
      $configuration: '@tracker_config'
